/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // documentationSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'index',
    {
      type: 'category',
      label: 'Learn',
      collapsed: false,
      collapsible: false,
      items: [
        'learn/about',
        'learn/how-it-works',
        'learn/tokenomics',
        {
          type: 'category',
          label: 'Network',
          items: [
            'learn/network/overview',
            'learn/network/benchmarks',
            'learn/network/node-distribution-map',
            'learn/network/application-layer',
            'learn/network/blockstore',
            'learn/network/client-libraries',
            'learn/network/epoch-synchronizer',
            'learn/network/handshake',
            {
              type: 'category',
              label: 'Services',
              items: [
                'learn/network/services/dynamic-service-loader',
                'learn/network/services/development',
                'learn/network/services/support',
              ],
            },
            {
              type: 'category',
              label: 'RPC',
              items: [
                'learn/network/rpc/interface',
              ],
            },
            'learn/ports',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Build',
      items: [
        {
          type: 'doc',
          id: 'build/index',
        },
      ],
    },
  ],
};

module.exports = sidebars;
